### PR TITLE
fixed donate button

### LINKED ISSUE #41: Donate Button Bug
fix the color. The color is in tailwind config. It should be bg-hsp-green. Also fix the font and font weight to match like the Figma.

### PR DESCRIPTION
**Pull request by charleenschen**
image

### CODE REVIEW

File: src/components/donate/Donate.js [hunk 1]
```diff
@@ -5,7 +5,7 @@ const Donate = () => {
   return (
     <Link
       href="#"
-      className="bg-green-600 text-white text-2xl font-bold text-decoration-line: underline flex justify-center items-center rounded-3xl min-w-fit px-4 min-h-fit py-1 hover:scale-110"
+      className="bg-hsp-green text-white text-[60px] font-urbanist font-black underline flex justify-center items-center rounded-[40.5rem] w-[364] h-[81] my-7 px-2.5 py-0 decoration-1 underline-offset-4 hover:scale-110"
```
Comment (rfairooz) [inline src/components/donate/Donate.js]: so this is good! instead of hardcoding height and width, can you eye ball it and make min-w-fit and w-4/12 or something for the page. And also for text-[60px] make it text-3xl or anything that is closer to 60 px.

File: hsp-website.code-workspace [hunk 2]
```diff
@@ -0,0 +1,7 @@
+{
```
Comment (rfairooz) [inline hsp-website.code-workspace]: can you try pushing again? I think you pushed the workspace accidentally.

File: src/components/donate/Table.js [hunk 3]
```diff
@@ -1,7 +1,115 @@
 import React from "react";
 
 const Table = () => {
-  return <div>Table</div>;
+  return (
```
Comment (rfairooz) [inline src/components/donate/Table.js]: the table should not be part of your commit. Check and push again

File: src/components/donate/Donate.js [hunk 4]
```diff
@@ -5,7 +5,7 @@ const Donate = () => {
   return (
     <Link
       href="#"
-      className="bg-green-600 text-white text-2xl font-bold text-decoration-line: underline flex justify-center items-center rounded-3xl min-w-fit px-4 min-h-fit py-1 hover:scale-110"
+      className="bg-hsp-green text-white text-6xl font-urbanist font-black underline flex justify-center items-center rounded-[40.5rem] min-w-fit h-20 my-7 px-2.5 py-0 decoration-1 underline-offset-4 hover:scale-110"
```
Comment (rfairooz) [inline src/components/donate/Donate.js]: rounded-40.5 rem cannot be hard coded. Change to 2xl or whichever value matches the most.

**Review by rfairooz — APPROVED** [review]
